version: "3.9"

services:
  library:
    image: node:16
    working_dir: /app
    command: bash -c "yarn && yarn start:dev"
    volumes:
      - .:/app:z
    container_name: library
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mongodb://root:example@mongo:27017/library

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - library-data:/data/db
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: library

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: ""

volumes:
  library-data: