swagger: '2.0'
info:
    title: Swagger
    description: Swagger API sample
    version: 1.0.0
basePath: /api
paths:
    /swagger:
        get:
            summary: Swagger
            responses:
                200:
                    description: Swagger
    /user:
        post:
            summary: Create a new user
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - in: body
                  name: body
                  description: User object
                  required: true
                  schema:
                      type: object
                      properties:
                          name:
                              type: string
                          userName:
                              type: string
                          password:
                              type: string
                          activated:
                              type: boolean
                          email:
                              type: string
                      required:
                          - name
                          - userName
                          - password
                          - activated
                          - email
            responses:
                201:
                    description: User created successfully
                400:
                    description: Bad request
        get:
            summary: Get all users
            produces:
                - application/json
            responses:
                200:
                    description: A list of users
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/User'
    /user/{id}:
        get:
            summary: Get a user by ID
            produces:
                - application/json
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                200:
                    description: A single user
                    schema:
                        $ref: '#/definitions/User'
                404:
                    description: User not found
        patch:
            summary: Update user status
            consumes:
                - application/json
            produces:
                - application/json
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Update operation
                  required: true
                  schema:
                      type: object
                      properties:
                          operation:
                              type: string
                              enum:
                                  - enable
                                  - disable
                      required:
                          - operation
            responses:
                200:
                    description: User status updated successfully
                400:
                    description: Bad request
definitions:
    User:
        type: object
        properties:
            _id:
                type: string
            name:
                type: string
            userName:
                type: string
            password:
                type: string
            activated:
                type: boolean
            email:
                type: string
